#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x57,0xd4,0xc3,0x9e,0x20,0x29,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x57,0xd4,0xc3,0x9e,0x47,0x39,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
